// Freera — i18n translations (EN / DE / ES)
window.FREERA_LANG = {
  en: {
    nav_home:'Home', nav_services:'Services', nav_about:'About', nav_contact:'Contact', nav_book:'Book a call',
    hero_eyebrow:'AI automation consultancy',
    hero_title:'Smart automation for businesses <span class="highlight">with real work to do.</span>',
    hero_lead:'We bring real, working AI into small and mid-sized businesses. Customer support, emails, documents, follow-ups — automated. Your team gets their time back. Your customers get faster service.',
    hero_cta:'Book a free call', hero_cta2:'See what we do',
    val1:'Live in 2 weeks', val2:'Working with SMEs globally', val3:'Plain-English, zero jargon', val4:'GDPR &amp; privacy-first',
    marquee_label:'Trusted by early partners',
    s_eyebrow:'What we do',
    s_title:'Five places AI can quietly transform <span class="italic">your day-to-day.</span>',
    s_lead:'We focus on the work that drains small teams — and where AI delivers fast, measurable wins. No moonshots, no hype.',
    svc1_title:'AI Audit &amp; Roadmap', svc1_body:'We shadow your team, find every repetitive task, and hand you a prioritised plan with quick wins and long-term opportunities.',
    svc2_title:'Customer Support Automation', svc2_body:'AI agents that handle your customer queries, live chat, ticket triage and follow-ups — around the clock, in your brand's voice.',
    svc3_title:'Document Automation', svc3_body:'Contracts, reports, proposals, SOPs — generated in seconds from your templates and data. Consistent, on-brand, effortless.',
    svc4_title:'Email &amp; Inbox Automation', svc4_body:'Smart triage, auto-responses, lead routing, follow-up sequences. Get your team out of the inbox and back to real work.',
    svc5_title:'Sales &amp; Marketing / SEO', svc5_body:'AI-powered lead nurturing, outreach sequences, content generation and on-page SEO optimisation — working while you focus on closing deals.',
    svc6_title:'Custom Workflow Automation', svc6_body:'Connect your tools and stitch them together. End-to-end flows from enquiry to invoice to CRM — running themselves.',
    svc7_title:'Something else?', svc7_body:"If it's repetitive, data-driven or rules-based, there's probably a way to automate it. Let's build something that fits your exact operation.",
    svc7_cta:'Start a conversation →',
    who_eyebrow:'Who we help',
    who_title:'Built for the businesses <span class="italic">drowning in admin.</span>',
    who_lead:'We work with SMEs whose teams spend more time on repetitive work than on the work that actually grows the business. If that sounds familiar, we should talk.',
    t_eyebrow:'What partners say',
    t_title:'Small teams, <span class="italic">real results.</span>',
    t1:'"Freera built us an AI support system that handles customer queries in four languages. What used to pile up overnight now gets answered and resolved automatically."',
    t2:'"Registration used to take our small team an entire weekend. Freera automated the whole flow — forms, payments, confirmations. Now it just runs."',
    t3:'"We were sceptical about AI for a clinic — our patients are older, our data is sensitive. Freera understood that from day one. Our admin hours are down 40%."',
    p_eyebrow:'How it works',
    p_title:'A process that <span class="italic">doesn\'t feel like one.</span>',
    step1_h:'Discovery call', step1_p:'A free 30-minute conversation. We learn your business, your tools, your biggest time sinks.',
    step2_h:'Audit &amp; plan', step2_p:'We map your workflows, spot the highest-ROI automations, and build you a clear roadmap.',
    step3_h:'Build &amp; launch', step3_p:'We implement in small, reviewable pieces. You see progress every week. No big-bang surprises.',
    step4_h:'Support &amp; improve', step4_p:'We stay on as needed — tweaking, expanding, training your team. You\'re never left stranded.',
    stat1_n:'20+', stat1_l:'Hours saved per week, on average, in our engagements',
    stat2_n:'2',   stat2_l:'Weeks from kick-off to first automation live',
    stat3_n:'100%',stat3_l:'Custom-built. No cookie-cutter templates.',
    stat4_n:'∞',   stat4_l:'Industries we\'re curious about. Yours included.',
    why_eyebrow:'Why Freera',
    why_title:'We\'re not a tech vendor. <span class="italic">We\'re partners.</span>',
    why1_h:'SME-first, always', why1_p:'We don\'t chase enterprise contracts. Our whole approach — pricing, pace, support — is built for smaller teams.',
    why2_h:'Plain English', why2_p:'No jargon, no buzzwords, no "synergising your AI stack." We explain what we\'re doing and why. Clearly.',
    why3_h:'ROI or it didn\'t happen', why3_p:'Every automation we build has to save time or make money. If we can\'t measure the value, we don\'t build it.',
    cta_title:'Ready to get your time back?',
    cta_body:'Free 30-minute call. No sales pitch. We\'ll take a look at your business and tell you — honestly — where AI could help and where it can\'t.',
    cta_btn:'Book your free call',
    footer_tagline:'AI automation consultancy for small and mid-sized businesses, everywhere.',
    footer_company:'Company', footer_services:'Services', footer_contact_h:'Get in touch',
    footer_copy:'© 2026 Freera Consultancy. All rights reserved.',
    footer_legal:'Privacy &amp; Imprint',
  },

  de: {
    nav_home:'Startseite', nav_services:'Leistungen', nav_about:'Über uns', nav_contact:'Kontakt', nav_book:'Termin buchen',
    hero_eyebrow:'KI-Automatisierungsberatung',
    hero_title:'Smarte Automatisierung für Unternehmen <span class="highlight">mit echten Aufgaben.</span>',
    hero_lead:'Wir bringen echte, funktionierende KI in kleine und mittelständische Unternehmen. Kundensupport, E-Mails, Dokumente, Follow-ups — automatisiert. Ihr Team gewinnt Zeit zurück. Ihre Kunden erhalten schnelleren Service.',
    hero_cta:'Kostenloses Gespräch buchen', hero_cta2:'Was wir tun',
    val1:'Live in 2 Wochen', val2:'KMUs weltweit', val3:'Klare Sprache, kein Fachjargon', val4:'DSGVO &amp; Datenschutz',
    marquee_label:'Unsere frühen Partner',
    s_eyebrow:'Was wir tun',
    s_title:'Fünf Bereiche, in denen KI Ihren Alltag <span class="italic">still verändert.</span>',
    s_lead:'Wir konzentrieren uns auf die Arbeit, die kleine Teams ausbremst — und wo KI schnelle, messbare Ergebnisse liefert. Keine Versprechen, keine Hype.',
    svc1_title:'KI-Audit &amp; Fahrplan', svc1_body:'Wir analysieren Ihre Abläufe, finden jede Routineaufgabe und übergeben Ihnen einen priorisierten Plan mit Quick Wins und langfristigen Chancen.',
    svc2_title:'Kundensupport-Automatisierung', svc2_body:'KI-Agenten, die Kundenanfragen, Live-Chat, Ticket-Triage und Follow-ups rund um die Uhr in Ihrer Markenstimme bearbeiten.',
    svc3_title:'Dokumentenautomatisierung', svc3_body:'Verträge, Berichte, Angebote, SOPs — in Sekunden aus Ihren Vorlagen und Daten generiert. Konsistent, markenkonform, mühelos.',
    svc4_title:'E-Mail &amp; Posteingang', svc4_body:'Intelligente Triage, automatische Antworten, Lead-Routing, Follow-up-Sequenzen. Befreien Sie Ihr Team vom Posteingang.',
    svc5_title:'Vertrieb &amp; Marketing / SEO', svc5_body:'KI-gestützte Lead-Pflege, Outreach-Sequenzen, Content-Erstellung und On-Page-SEO-Optimierung — während Sie sich aufs Abschließen konzentrieren.',
    svc6_title:'Individuelle Workflow-Automatisierung', svc6_body:'Verbinden Sie Ihre Tools. End-to-End-Prozesse von der Anfrage über die Rechnung bis zum CRM — vollautomatisch.',
    svc7_title:'Etwas anderes?', svc7_body:'Wenn es repetitiv, datengetrieben oder regelbasiert ist, lässt es sich wahrscheinlich automatisieren. Lassen Sie uns etwas bauen, das genau zu Ihnen passt.',
    svc7_cta:'Gespräch starten →',
    who_eyebrow:'Wen wir unterstützen',
    who_title:'Für Unternehmen gebaut, <span class="italic">die in der Verwaltung ertrinken.</span>',
    who_lead:'Wir arbeiten mit KMUs, deren Teams mehr Zeit mit Routinearbeiten verbringen als mit dem, was das Unternehmen wirklich voranbringt.',
    t_eyebrow:'Was Partner sagen',
    t_title:'Kleine Teams, <span class="italic">echte Ergebnisse.</span>',
    t1:'„Freera hat uns ein KI-Supportsystem gebaut, das Kundenanfragen in vier Sprachen bearbeitet. Was sich früher über Nacht anhäufte, wird jetzt automatisch beantwortet."',
    t2:'„Die Anmeldung beanspruchte früher ein ganzes Wochenende unseres kleinen Teams. Freera automatisierte den gesamten Ablauf — Formulare, Zahlungen, Bestätigungen. Jetzt läuft es einfach."',
    t3:'„Wir waren skeptisch gegenüber KI in einer Klinik — unsere Patienten sind älter, unsere Daten sensibel. Freera hat das von Anfang an verstanden. Unsere Verwaltungsstunden sind um 40 % gesunken."',
    p_eyebrow:'So funktioniert es',
    p_title:'Ein Prozess, der sich <span class="italic">nicht wie einer anfühlt.</span>',
    step1_h:'Erstgespräch', step1_p:'Ein kostenloses 30-minütiges Gespräch. Wir lernen Ihr Unternehmen, Ihre Tools und Ihre größten Zeitfresser kennen.',
    step2_h:'Audit &amp; Plan', step2_p:'Wir kartieren Ihre Workflows, identifizieren die ROI-stärksten Automatisierungen und erstellen eine klare Roadmap.',
    step3_h:'Aufbau &amp; Launch', step3_p:'Wir implementieren in kleinen, nachvollziehbaren Schritten. Sie sehen jeden Fortschritt. Keine großen Überraschungen.',
    step4_h:'Support &amp; Weiterentwicklung', step4_p:'Wir bleiben dabei — anpassen, erweitern, Ihr Team schulen. Sie werden nie allein gelassen.',
    stat1_n:'20+', stat1_l:'Stunden pro Woche eingespart, im Durchschnitt',
    stat2_n:'2',   stat2_l:'Wochen vom Start bis zur ersten Live-Automatisierung',
    stat3_n:'100%',stat3_l:'Individuell entwickelt. Keine Vorlagen von der Stange.',
    stat4_n:'∞',   stat4_l:'Branchen, die uns interessieren. Auch Ihre.',
    why_eyebrow:'Warum Freera',
    why_title:'Wir sind kein Technologielieferant. <span class="italic">Wir sind Partner.</span>',
    why1_h:'KMU-first, immer', why1_p:'Wir jagen keine Enterprise-Aufträge. Unser gesamter Ansatz — Preisgestaltung, Tempo, Support — ist für kleinere Teams entwickelt.',
    why2_h:'Klare Sprache', why2_p:'Kein Fachjargon, keine Buzzwords. Wir erklären, was wir tun und warum. Verständlich.',
    why3_h:'ROI oder es war nichts', why3_p:'Jede Automatisierung muss Zeit sparen oder Geld einbringen. Wenn wir den Wert nicht messen können, bauen wir sie nicht.',
    cta_title:'Bereit, Ihre Zeit zurückzugewinnen?',
    cta_body:'Kostenloser 30-minütiger Anruf. Kein Verkaufsgespräch. Wir schauen uns Ihr Unternehmen an und sagen Ihnen ehrlich, wo KI helfen kann und wo nicht.',
    cta_btn:'Kostenloses Gespräch buchen',
    footer_tagline:'KI-Automatisierungsberatung für kleine und mittelständische Unternehmen weltweit.',
    footer_company:'Unternehmen', footer_services:'Leistungen', footer_contact_h:'Kontakt',
    footer_copy:'© 2026 Freera Consultancy. Alle Rechte vorbehalten.',
    footer_legal:'Datenschutz &amp; Impressum',
  },

  es: {
    nav_home:'Inicio', nav_services:'Servicios', nav_about:'Nosotros', nav_contact:'Contacto', nav_book:'Reservar llamada',
    hero_eyebrow:'Consultoría de automatización con IA',
    hero_title:'Automatización inteligente para empresas <span class="highlight">con trabajo real.</span>',
    hero_lead:'Llevamos IA real y funcional a pequeñas y medianas empresas. Atención al cliente, correos, documentos, seguimientos — automatizados. Tu equipo recupera su tiempo. Tus clientes reciben un servicio más rápido.',
    hero_cta:'Reservar llamada gratuita', hero_cta2:'Ver qué hacemos',
    val1:'En marcha en 2 semanas', val2:'Pymes en todo el mundo', val3:'Lenguaje claro, sin tecnicismos', val4:'RGPD y privacidad',
    marquee_label:'Con la confianza de nuestros socios',
    s_eyebrow:'Qué hacemos',
    s_title:'Cinco áreas donde la IA puede transformar <span class="italic">tu día a día.</span>',
    s_lead:'Nos enfocamos en el trabajo que agota a los equipos pequeños — y donde la IA ofrece resultados rápidos y medibles. Sin promesas vacías.',
    svc1_title:'Auditoría e hoja de ruta de IA', svc1_body:'Analizamos tu equipo, encontramos cada tarea repetitiva y te entregamos un plan priorizado con victorias rápidas y oportunidades a largo plazo.',
    svc2_title:'Automatización del soporte al cliente', svc2_body:'Agentes de IA que gestionan consultas, chat en vivo, triaje de tickets y seguimientos — las 24 horas, con la voz de tu marca.',
    svc3_title:'Automatización de documentos', svc3_body:'Contratos, informes, propuestas, SOPs — generados en segundos a partir de tus plantillas y datos. Consistente, en línea con tu marca, sin esfuerzo.',
    svc4_title:'Automatización de correos', svc4_body:'Triaje inteligente, respuestas automáticas, enrutamiento de leads, secuencias de seguimiento. Libera a tu equipo de la bandeja de entrada.',
    svc5_title:'Ventas &amp; Marketing / SEO', svc5_body:'Nutrición de leads, secuencias de alcance, generación de contenido y optimización SEO — todo con IA, mientras te concentras en cerrar negocios.',
    svc6_title:'Automatización de flujos personalizados', svc6_body:'Conecta tus herramientas. Flujos de extremo a extremo desde la consulta hasta la factura y el CRM — funcionando solos.',
    svc7_title:'¿Algo más?', svc7_body:'Si es repetitivo, basado en datos o en reglas, probablemente se pueda automatizar. Construyamos algo que encaje exactamente con tu operación.',
    svc7_cta:'Iniciar conversación →',
    who_eyebrow:'A quién ayudamos',
    who_title:'Para las empresas que se <span class="italic">ahogan en administración.</span>',
    who_lead:'Trabajamos con pymes cuyos equipos pasan más tiempo en trabajo repetitivo que en lo que realmente hace crecer el negocio.',
    t_eyebrow:'Lo que dicen los socios',
    t_title:'Equipos pequeños, <span class="italic">resultados reales.</span>',
    t1:'"Freera nos construyó un sistema de soporte con IA que gestiona consultas en cuatro idiomas. Lo que antes se acumulaba por la noche ahora se responde automáticamente."',
    t2:'"El registro solía llevarnos un fin de semana entero. Freera automatizó todo el proceso — formularios, pagos, confirmaciones. Ahora simplemente funciona."',
    t3:'"Éramos escépticos sobre la IA en una clínica — nuestros pacientes son mayores, los datos son sensibles. Freera lo entendió desde el primer día. Nuestras horas de administración bajaron un 40%."',
    p_eyebrow:'Cómo funciona',
    p_title:'Un proceso que <span class="italic">no parece uno.</span>',
    step1_h:'Llamada de descubrimiento', step1_p:'Una conversación gratuita de 30 minutos. Aprendemos sobre tu negocio, tus herramientas y tus mayores pérdidas de tiempo.',
    step2_h:'Auditoría y plan', step2_p:'Mapeamos tus flujos de trabajo, identificamos las automatizaciones de mayor ROI y creamos una hoja de ruta clara.',
    step3_h:'Construcción y lanzamiento', step3_p:'Implementamos en piezas pequeñas y revisables. Ves el progreso cada semana. Sin grandes sorpresas.',
    step4_h:'Soporte y mejora', step4_p:'Seguimos disponibles — ajustando, ampliando, formando a tu equipo. Nunca te dejamos solo.',
    stat1_n:'20+', stat1_l:'Horas ahorradas por semana, en promedio',
    stat2_n:'2',   stat2_l:'Semanas desde el inicio hasta la primera automatización en vivo',
    stat3_n:'100%',stat3_l:'Desarrollado a medida. Sin plantillas genéricas.',
    stat4_n:'∞',   stat4_l:'Sectores que nos interesan. El tuyo también.',
    why_eyebrow:'Por qué Freera',
    why_title:'No somos un proveedor de tecnología. <span class="italic">Somos socios.</span>',
    why1_h:'Primero las pymes, siempre', why1_p:'No perseguimos contratos de grandes empresas. Todo nuestro enfoque — precios, ritmo, soporte — está diseñado para equipos más pequeños.',
    why2_h:'Lenguaje claro', why2_p:'Sin jerga, sin palabras de moda. Explicamos lo que hacemos y por qué. Con claridad.',
    why3_h:'ROI o no cuenta', why3_p:'Cada automatización que construimos debe ahorrar tiempo o generar dinero. Si no podemos medir el valor, no la construimos.',
    cta_title:'¿Listo para recuperar tu tiempo?',
    cta_body:'Llamada gratuita de 30 minutos. Sin discurso de ventas. Miramos tu negocio y te decimos honestamente dónde puede ayudar la IA y dónde no.',
    cta_btn:'Reservar tu llamada gratuita',
    footer_tagline:'Consultoría de automatización con IA para pequeñas y medianas empresas en todo el mundo.',
    footer_company:'Empresa', footer_services:'Servicios', footer_contact_h:'Contacto',
    footer_copy:'© 2026 Freera Consultancy. Todos los derechos reservados.',
    footer_legal:'Privacidad &amp; Aviso legal',
  }
};

// Apply translations to elements with data-i18n attribute
window.applyLang = function(lang) {
  var t = window.FREERA_LANG[lang] || window.FREERA_LANG.en;
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  // Update html lang attribute
  document.documentElement.lang = lang;
  // Persist
  try { localStorage.setItem('freera_lang', lang); } catch(e) {}
  // Update switcher buttons
  document.querySelectorAll('.lang-btn').forEach(function(b) {
    b.classList.toggle('active', b.getAttribute('data-lang') === lang);
  });
};

window.initLang = function() {
  var saved = 'en';
  try { saved = localStorage.getItem('freera_lang') || 'en'; } catch(e) {}
  window.applyLang(saved);
};
